### ISSUE TITLE
New Version of TDLib breaks existing pre compiled build

### ISSUE THREAD

**Issue by cplankl** [br0tda/tdlib_raspberry#1]
Hi there,

Telegram released a new version of tdlib. Is there any chance that you could provide a new Version of the libtdjson.so file?

**Comment by br0tda** [comment]
Hi, please try following these commands from your Raspberry

git clone https://github.com/tdlib/td.git
cd td
rm -rf build
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=../tdlib ..
cmake --build . --target install
cd ..
cd ..
ls -l td/tdlib

You should be able to compile it. If there's any error please let me know. I'll try to compile again it, but I'll take some weeks for me to work on it.

**Comment by br0tda** [comment]
Hi, please try these commands from your Raspberry

git clone https://github.com/tdlib/td.git
cd td
rm -rf build
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=../tdlib ..
cmake --build . --target install
cd ..
cd ..
ls -l td/tdlib

You should be able to compile it. If there's any error please let me know. I'll try to compile too, but it will take some days to work on it.

**Comment by cplankl** [comment]
Ok finally it built on my RPi2. But I had to do the following steps:

apt-get update
apt-get upgrade
apt-get install make git zlib1g-dev libssl-dev gperf php-cli cmake g++
exit
git clone https://github.com/tdlib/td.git
cd td
rm -rf build
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=../tdlib ..
cmake --build . --target prepare_cross_compiling
cd ..
php SplitSource.php
cd build
cmake --build . --target install
cd ..
php SplitSource.php --undo
cd ..
ls -l td/tdlib

SplitSources.php was necessary because the RPi2 has just 1 GB of RAM and otherwise it crashed. 
I still also had to apply the manual change here: https://github.com/tdlib/td/issues/1191#issue-700415611

**Comment by br0tda** [comment]
Sounds good! 
I'll use your guide and release the new version as soon as possible! 

Have a nice day

**Comment by cplankl** [comment]
My tests where successful as far as I have seen! 

Thanks!
